### ISSUE TITLE
Provide default configs for fixed URLs or remove them from configs.

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/RADAR-RedcapIntegration#30]
Some of the configs mentioned in current [radar.yml](https://github.com/RADAR-base/RADAR-RedcapIntegration/blob/dev/radar.yml) are quite extensive for a new user and some fixed URLs can be removed e.g. token URL, projects URL, subjects URL assuming this will not change on the MP side.
Plus, do we really use the first two configs for any useful purpose? 
A workaround could be to configure these URLs with MP url config and provide a default config in the yml file and allow overriding when necessary.

**Comment by yatharthranjan** [comment]
Ok yes, I agree some are fixed and can be removed from the config. 
I don't think the first two have any importance. There were added by Francesco not sure why. I will take a look.
